apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: klizvbec8-python 
  janus-idp.io/tekton: klizvbec8-python
  backstage.io/kubernetes-id: klizvbec8-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: klizvbec8-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml